### ISSUE TITLE
Deploy Stratos on kubecf

### ISSUE THREAD

**Issue by gaktive** [SUSE/kubecf#199]
**Is your feature request related to a problem? Please describe.**
The Stratos Console works on scf. We need to make sure it runs on kubecf.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fargozhu** [comment]
Stratos (both versions) deployed with success with KubeCF 0.1.0 on GKE 1.4.1.

**Comment by fargozhu** [comment]
The verification should include UAA integration.

**Comment by jimmykarily** [comment]
We deployed Stratos and used the following values to connect to the UAA (cluster is a kind one):

```
env:
   DOMAIN: 172.17.0.2
   UAA_HOST: uaa.172.17.0.2.nip.io
   UAA_PORT: 443
   UAA_ZONE: ~
```
it turns out that Stratos expects `UAA_ZONE` to be set otherwise it is set to `scf` : https://github.com/cloudfoundry/stratos/blob/9c4422850042249c55a5ee925fcbbe477891d16c/deploy/kubernetes/console/templates/__helpers.tpl#L48

on kubecf, we don't setup identity zones like we did in scf (https://github.com/SUSE/scf/blob/develop/src/scf-release/jobs/uaa-create-user/templates/run.erb#L80). The `admin` user is created on the "root" identity zone (no subdomain) but Stratos can't authenticate against that (always assumes a zone).

So we verified that Stratos can authenticate with UAA but in order to work with kubecf one of the 2 must happen:

- root identity zone can be used in Stratos (cc @nwmac)
or
- we setup an identity zone in kubecf which we can then use as the UAA_ZONE setting when deploying Stratos.

**Comment by fargozhu** [comment]
blocked by https://github.com/cloudfoundry/stratos/issues/4101

**Comment by thardeck** [comment]
I installed Stratos 2.7.0 with helm, and used the UI to connect to kubecf.

You have to specify the endpoint URL without a `/` at the end. The client id is `cf`, the client secret is empty, the admin username is `admin` and the admin password is the actual cf password.

If unknown it can be extracted with `echo $(kubectl get secrets -n kubecf kubecf.var-cf-admin-password -o json | jq -r .data.password | base64 -d)`.

In Stratos you can login with the same user and password combination or probably any other uaa combination which is part of the uaa group specified during the Stratos setup.
