### ISSUE TITLE
Reusing an external database after reinstalling kubecf does not work

### ISSUE THREAD

**Issue by f0rmiga** [SUSE/kubecf#233]
**Describe the bug**

On an attempt to reuse the external database, a kubecf reinstall won't work.

**To Reproduce**

- Deploy kubecf using an external database.
- Run smoke-tests.
- Delete kubecf installation.
- Deploy kubecf again without changing any values.
- Run smoke-tests - it will fail.

**Expected behavior**

Given the proper values, the smoke-tests on the reinstallation should work.

**Comment by andreas-kupries** [comment]
Hm. I wonder if the smoke-tests do not handle that the database has had smoke tests already run on it ... No, that cannot be it. Otherwise simply running smoke tests twice on an existing kubecf would fail the second time as well.

Maybe the migrations from the second installation disturb something ?

I am speculating in a vacuum. IOW I have no real information here. I believe that it would be good to attach information (logs, etc.) on how the smoke tests are failing after the reinstallation. That will also help in reproduction, i.e. to determine if a failure seen in repro is the same failure as described in the report.

**Comment by f0rmiga** [comment]
We need a story to actually document the steps to deal with the data in an external database after the kubecf installation was deleted.
