### ISSUE TITLE
Diego-api cannot be scaled to two instances

### ISSUE THREAD

**Issue by jkbschmid** [SUSE/kubecf#279]
**Describe the bug**
When scaling diego-api to 2 instances, `diego-api-1` does not become ready, because it requires a lock that `diego-api-0` possesses:
```
$ kubectl logs -n kubecf kubecf-diego-api-1 bbs-bbs
...
{"timestamp":"2019-12-19T11:27:51.986052507Z","level":"info","source":"bbs","message":"bbs.locket-lock.started","data":{"lock":{"key":"bbs","owner":"diego-api-1","type":"lock","type_code":1},"session":"4","ttl_in_seconds":15}}
{"timestamp":"2019-12-19T11:27:51.992993235Z","level":"error","source":"bbs","message":"bbs.locket-lock.failed-to-acquire-lock","data":{"error":"rpc error: code = AlreadyExists desc = lock-collision","lock":{"key":"bbs","owner":"diego-api-1","type":"lock","type_code":1},"lock-owner":"diego-api-0","request-uuid":"1d8291a4-3572-4c65-4079-629e1a6f0464","session":"4","ttl_in_seconds":15}}
```

Note: Scaling diego-api used to work until at least kubecf  6919a3de229063aa753a9e1b35cb7c43a60a5d15.

**To Reproduce**
Install kubecf with diego-api scaled to two instances.

**Environment**
 - kubecf master: 1fddab50d183876cb9b0699fa3437999a294fb91
 - cf-operator master

**Comment by f0rmiga** [comment]
@jkbschmid This is the expected behaviour. We got a fix for the BBS readiness probe here: https://github.com/SUSE/kubecf/pull/273. Before that, it was not scaling properly, as it should work in the active-passive HA mode. The log you posted was there before the bug fix. You can assert that it is working properly in active-passive by deleting the pod `diego-api-0` and checking that `diego-api-1` acquires the lock, and then the readiness probes start to succeed.
