### ISSUE TITLE
Support explicit PSP

### ISSUE THREAD

**Issue by f0rmiga** [SUSE/kubecf#306]
**Is your feature request related to a problem? Please describe.**

We need to be able to explicitly provide a PSP to be used by each instance group.

**Describe the solution you'd like**

A mechanism on kubecf or cf-operator to provide the PSP.

**Additional context**

Depending on the k8s platform, kubecf doesn't work because of wrong PSP settings.

**Comment by fargozhu** [comment]
@f0rmiga can you help me trying to understand the problem that we are trying to solve here?

**Comment by jandubois** [comment]
This seems like a misunderstanding to me: you cannot explicitly specify a PSP for a particular pod. You need to make sure to specify a `securityContext` that lists *all* capabilities required by the pod. That way the admission controller will only validate the pod against a PSP that allows access to all these capabilities.

I know that PSP can also provide default capabilities to pods. However, given that PSPs will be tested in alphabetical order, this seems like a misfeature and should not be relied on. Kube will always test all authorized PSPs in alphabetical order and choose the first one that validates the `securityContext` of the pod.

So you are always at risk of the cluster providing a PSP called `AAAA` (or anything alphabetical before your own PSP name), that is authorized for all users, because it could be chosen instead of your "assigned" policy, as long as it validates your `securityContext` requirements. In that case your pod will not get the additional defaults provided by your "own" PSP.

**Comment by troytop** [comment]
This bug was filed to address an issue I hit getting KubeCF to deploy. The specific capability needed was `NET_BIND_SERVICE`, and we had to add an `aaa-suse.caasp.psp.unprivileged` psp with this to get things working.  Not sure how the fix needs to be implemented, but this is the problem that sparked the bug.

**Comment by troytop** [comment]
Looking back, I think the issue was that kubecf ran using an `nginx-ingress` psp before I created the new one and *that* psp was missing something. It might have been the `RunAsAny` rules that were required.

**Comment by jandubois** [comment]
The pod that needs that capability has to list it in the `securityContext`:

```
  spec:
      securityContext:
        capabilities:
          add:
          - NET_BIND_SERVICE
```

That way it will not validate against a PSP that doesn't allow it.

**Comment by jandubois** [comment]
> It might have been the `RunAsAny` rules that were required.

The solution is always the same: the `securityContext` needs to list what the pod needs.

**Comment by troytop** [comment]
Sure. Just trying to figure out what was not listed. The bits service (I think) did not declare something that was necessary, which is why it used the `nginx-ingress` psp. For posterity, here are the `spec` sections for both:

```
troyt@phoenix:/tmp $ kubectl get psp aaa-suse.caasp.psp.unprivileged -o yaml |yq .spec  # works
{
  "allowPrivilegeEscalation": false,
  "allowedCapabilities": [
    "NET_BIND_SERVICE"
  ],
  "allowedHostPaths": [
    {
      "pathPrefix": "/opt/kubernetes-hostpath-volumes"
    }
  ],
  "defaultAllowPrivilegeEscalation": false,
  "fsGroup": {
    "rule": "RunAsAny"
  },
  "hostPorts": [
    {
      "max": 65535,
      "min": 0
    }
  ],
  "runAsUser": {
    "rule": "RunAsAny"
  },
  "seLinux": {
    "rule": "RunAsAny"
  },
  "supplementalGroups": {
    "rule": "RunAsAny"
  },
  "volumes": [
    "configMap",
    "secret",
    "emptyDir",
    "downwardAPI",
    "projected",
    "persistentVolumeClaim",
    "nfs",
    "rbd",
    "cephFS",
    "glusterfs",
    "fc",
    "iscsi",
    "cinder",
    "gcePersistentDisk",
    "awsElasticBlockStore",
    "azureDisk",
    "azureFile",
    "vsphereVolume"
  ]
}
troyt@phoenix:/tmp $ kubectl get psp nginx-ingress -o yaml |yq .spec  # does not work
{
  "allowPrivilegeEscalation": true,
  "allowedCapabilities": [
    "NET_BIND_SERVICE"
  ],
  "fsGroup": {
    "ranges": [
      {
        "max": 65535,
        "min": 1
      }
    ],
    "rule": "MustRunAs"
  },
  "hostPorts": [
    {
      "max": 65535,
      "min": 1
    }
  ],
  "runAsUser": {
    "rule": "MustRunAsNonRoot"
  },
  "seLinux": {
    "rule": "RunAsAny"
  },
  "supplementalGroups": {
    "ranges": [
      {
        "max": 65535,
        "min": 1
      }
    ],
    "rule": "MustRunAs"
  },
  "volumes": [
    "configMap",
    "secret"
  ]
}
```

**Comment by jandubois** [comment]
@ttopnik These are the specs of the PSPs. It is the *pod* spec that includes the `securityContext`, that will be matched against the PSPs. Please include that data as well, then we can try to understand why it validated against the wrong PSP.

**Comment by troytop** [comment]
```
$ kubectl get pod -n kubecf kubecf-bits-0 -o yaml |yq -a .spec.containers[].securityContext
{
  "allowPrivilegeEscalation": false,
  "privileged": false,
  "runAsUser": 0
}
{
  "allowPrivilegeEscalation": false,
  "privileged": false,
  "runAsUser": 0
}
{
  "allowPrivilegeEscalation": false,
  "capabilities": {
    "add": [
      "NET_BIND_SERVICE"
    ]
  },
  "privileged": false,
  "runAsUser": 0
}
{
  "allowPrivilegeEscalation": false,
  "privileged": false,
  "runAsUser": 0
}
{
  "allowPrivilegeEscalation": false,
  "privileged": false,
  "runAsUser": 0
}
{
  "allowPrivilegeEscalation": false,
  "runAsUser": 0
}
```

Damnit Jim, I'm a Product Manager not a ....

**Comment by jandubois** [comment]
Ok, now I'm confused: All containers specify `"runAsUser": 0`, so they should not be able to validate against the `nginx-ingress` PSP because it has:

```
  "runAsUser": {
    "rule": "MustRunAsNonRoot"
  },
```

**Comment by f0rmiga** [comment]
Turns out that we need to allow the pods to use a PSP via a role. https://github.com/SUSE/kubecf/pull/347 fixes this.
