### ISSUE TITLE
Update README with pointers to installation docs

### ISSUE THREAD

**Issue by viovanov** [SUSE/kubecf#74]
We need to provide links in the main README, otherwise our docs are hard to find.
As part of this, we should also cleanup our docs directories and docs themselves.

- [ ] Keep `./doc` just in the root of the project, and have sub-folders in there
- [ ] Make sure there's a path from README to any of the docs (can be through multiple hops)
- [ ] Consolidate and cleanup the docs themselves

**Comment by andreas-kupries** [comment]
Ref https://jira.suse.com/browse/CAP-891

**Comment by andreas-kupries** [comment]
Draft PR, incomplete: https://github.com/SUSE/kubecf/pull/87

**Comment by andreas-kupries** [comment]
@viovanov @f0rmiga Please have a look at the three files related to kubecf installation on master and give me feedback / guidance regarding consolidation. The files are:

  - __INSTALL.md__:

    Describes install based on Minikube or GKE direct + Operator from
    Release + Kubecf from Release, with things specific to Eirini and
    GKE ingress ? (loadbalancer ?)

  - __dev/kubecf/docs/installing.md__:

    Describes install based on minikube or kind, with operator from
    checkout + kubecf from checkout, with things specific to ingress
    via Nginx.

  - __doc/mok_brc.md__:

    Describes an install based on Minikube via Bazel + Operator from
    Release + Kubecf from Checkout.

The first two are the older, unsure which of these was first. They seem to try to describe multiple options at once, with some overlap (both mention minikube) and some not (One mentions kind, the other GKE), and each seem to have specific details around exposing the kubecf, and/or ingress and/or LBs.

The third comes from a first attempt at consolidation. My attempt at describing a single vertical without going into any options and complexity, all choices fixed (minikube, operator release, kubecf from checkout (because that is what we focus on for dev), nothing about ingress and the like).

I am strongly tempted to simply remove the first two.

Your thoughts ?

**Comment by f0rmiga** [comment]
@andreas-kupries I updated the `doc/mok_brc.md` file to use the Bazel target to deploy cf-operator.

I think we should move `doc/mok_brc.md` to `doc/dev/mok_brc.md` and have a generic `doc/install.md` that:

1. Describes the k8s requirements for running kubecf.
2. Describes how to deploy cf-operator. Right now, we should point people to look at `defs.bzl` to get the cf-operator chart that is validated with kubecf master.
3. Describes how to deploy kubecf using the latest published chart in the S3 bucket. This step should include options on how to deploy with Eirini and how to deploy with Diego, and also how to deploy with ingress controller and without ingress controller.
4. Has a section after the generic installation instructions on specifics for platforms, especially talking about public cloud providers (e.g. GKE).

For `dev/kubecf/docs/installing.md`, if everything is covered on `doc/mok_brc.md`, I don't see why we should keep it.

After you write `doc/install.md`, we can delete `INSTALL.md`.

**Comment by andreas-kupries** [comment]
@f0rmiga 

  - What are the k8s requirements for running kubecf ?
  - `def.bzl` Which of the seven files with that name are you thinking of ?
  - I believe that diego/eirini and ingress/not should be in a separate document about advanced installation topics.
  - Similarly the information about GKE and other public cloud providers.
  - This ties into me prefering the initial documents to be simple, straight forward, with the user not having to make any choices. Follow the recipe and you get something. After we can educate on the other possibilities.

**Comment by andreas-kupries** [comment]
Done with https://github.com/SUSE/kubecf/pull/87
